import { ArrowUpRight, CalendarDays, Crown, Radio, ShoppingBag, Sparkles, Trophy } from "lucide-react";
import { contentService } from "@/services/content.service";
import { Section } from "@/components/ui/section";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Avatar } from "@/components/ui/avatar";

export async function HomeSections(){const [videos,ranking]=await Promise.all([contentService.getLatestVideos(),contentService.getRanking()]);return <>
<Section eyebrow="EN DIRECTO" title="Ahora en SotaKun"><Card className="relative overflow-hidden p-7 md:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_30%,rgba(37,99,235,.22),transparent_35%)]"/><div className="relative grid items-center gap-8 md:grid-cols-[1.5fr_1fr]"><div><Badge className="border-red-400/20 bg-red-400/10 text-red-300"><Radio size={11} className="mr-1"/> LIVE</Badge><h3 className="mt-5 text-3xl font-black text-white">Noche de Santuario</h3><p className="mt-2 text-slate-400">Subiendo el ranking con la comunidad · Diablo IV</p><Button href="https://twitch.tv" className="mt-6">Ver directo <ArrowUpRight size={16}/></Button></div><div className="rounded-2xl border border-white/10 bg-black/30 p-6 text-center"><p className="text-5xl font-black text-white">1,284</p><p className="mt-2 text-xs font-bold tracking-widest text-slate-500 uppercase">espectadores ahora</p></div></div></Card></Section>
<Section eyebrow="CONTENIDO" title="Últimas transmisiones" description="Guías, retos y momentos memorables seleccionados para la comunidad."><div className="grid gap-5 md:grid-cols-3">{videos.map((v,i)=><Card className="group overflow-hidden" key={v.title}><div className={`video-art video-art-${i+1}`}><span className="grid size-13 place-items-center rounded-full border border-white/20 bg-black/40 text-white backdrop-blur"><ArrowUpRight/></span></div><div className="p-5"><span className="eyebrow">{v.eyebrow}</span><h3 className="mt-3 text-xl font-bold text-white group-hover:text-sky-300">{v.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{v.description}</p><p className="mt-4 text-xs text-slate-600">{v.meta}</p></div></Card>)}</div></Section>
<Section eyebrow="CLASIFICACIÓN" title="Los nombres en lo más alto"><div className="grid gap-5 md:grid-cols-3">{ranking.map((entry)=><Card className={`relative p-6 ${entry.position===1?"md:-translate-y-3 border-yellow-300/20":""}`} key={entry.name}><span className="absolute right-5 top-4 text-5xl font-black text-white/[.04]">0{entry.position}</span><div className="flex items-center gap-4"><Avatar name={entry.name} className="size-14"/><div><p className="font-black text-white">{entry.name}</p><Badge className="mt-1">{entry.badge}</Badge></div></div><div className="mt-7 flex items-end justify-between"><div><p className="text-3xl font-black" style={{color:entry.accent}}>{entry.points.toLocaleString("es-ES")}</p><p className="text-xs text-slate-600">puntos de comunidad</p></div>{entry.position===1?<Crown className="text-yellow-300"/>:<Trophy className="text-slate-500"/>}</div></Card>)}</div><Button href="/ranking" variant="secondary" className="mt-7">Ver ranking completo</Button></Section>
<Section eyebrow="SORTEO ACTIVO" title="Una reliquia espera dueño"><Card className="overflow-hidden"><div className="grid md:grid-cols-2"><div className="giveaway-art min-h-80"/><div className="flex flex-col justify-center p-8 md:p-12"><Badge className="w-fit border-yellow-300/20 bg-yellow-300/10 text-yellow-200"><Sparkles size={11} className="mr-1"/> EDICIÓN LIMITADA</Badge><h3 className="mt-5 text-3xl font-black text-white">Santuario Collector&apos;s Box</h3><p className="mt-3 leading-7 text-slate-400">Una pieza numerada, certificado digital y sorpresas exclusivas para un miembro de la comunidad.</p><div className="mt-6 flex items-center gap-3 text-sm text-slate-300"><CalendarDays size={17} className="text-sky-300"/> Termina en 04 días · 12:38:16</div><Button href="/sorteos" className="mt-7 w-fit">Participar ahora</Button></div></div></Card></Section>
<Section eyebrow="FORJADO PARA LA COMUNIDAD" title="Merch con historia"><div className="grid gap-5 md:grid-cols-[1.4fr_1fr]"><Card className="merch-art min-h-105 p-7"><Badge className="border-yellow-300/20 bg-yellow-300/10 text-yellow-200">DROP 01</Badge><div className="mt-60"><h3 className="text-3xl font-black text-white">The Founders Collection</h3><p className="mt-2 text-slate-400">Piezas numeradas con certificado de autenticidad.</p></div></Card><Card className="flex flex-col justify-between p-8"><ShoppingBag className="text-sky-300" size={34}/><div><p className="eyebrow">DISPONIBLE PRONTO</p><h3 className="mt-3 text-2xl font-black text-white">Cada objeto cuenta una historia</h3><p className="mt-3 leading-7 text-slate-400">Colecciones cuidadas, stock verificable y certificados QR ligados a cada propietario.</p><Button href="/merch" variant="secondary" className="mt-6">Explorar merch</Button></div></Card></div></Section>
<Section eyebrow="ÚLTIMAS NOTICIAS" title="El pulso de SotaKun"><div className="grid gap-5 md:grid-cols-3">{["La temporada cero comienza aquí","Nuevos rangos y recompensas","Roadmap de SotaKun 2026"].map((title,i)=><Card className="p-6" key={title}><span className="text-xs text-slate-600">{["COMUNIDAD","PLATAFORMA","DESARROLLO"][i]} · 5 MIN</span><h3 className="mt-4 text-xl font-black text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">Descubre las novedades, próximos eventos y todo lo que estamos construyendo juntos.</p><Button href="/noticias" variant="ghost" className="mt-5 px-0">Leer noticia <ArrowUpRight size={15}/></Button></Card>)}</div></Section>
</>}
