import { Award, BadgeCheck, Check, Clock3, Gift, MessageCircle, Radio, ShieldCheck, Sparkles, Trophy, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Section } from "@/components/ui/section";
import { siteConfig } from "@/config/site";
import type { YouTubeSnapshot } from "@/features/youtube/youtube.types";
import { formatCompact } from "@/utils/format-youtube";
import { getCurrentMilestone, getMilestoneProgress, giveawayHistory, giveawayMilestones, pointsRules } from "../giveaways.config";
import { NieblaGiveawaySection } from "./niebla-giveaway-section";

export function GiveawaysPage({ youtube, adminPanel }: { youtube: YouTubeSnapshot; adminPanel?: React.ReactNode }) {
  const subscribers = youtube.channel.subscriberCount;
  const current = getCurrentMilestone(subscribers);
  const progress = getMilestoneProgress(subscribers, current.subscribers);
  const remaining = Math.max(0, current.subscribers - subscribers);

  return <>
    <section className="hero-art border-b border-[#7c5b31]/35"><div className="shell py-20 text-center md:py-28"><Badge><Sparkles size={12} className="mr-1" /> EL CAMINO A LOS 1000</Badge><h1 className="display-title mx-auto mt-6 max-w-4xl text-5xl text-[#dfc89f] md:text-7xl">Tu participación<br/><span className="text-gradient">tiene valor.</span></h1><p className="mx-auto mt-6 max-w-2xl font-serif text-lg leading-8 text-[#9b8d78]">No premiamos solamente la suerte. Cada comentario, cada directo y cada aportación real aumenta tus posibilidades de ganar.</p><div className="mx-auto mt-10 max-w-3xl border border-[#876438]/50 bg-black/40 p-6 text-left backdrop-blur md:p-8"><div className="flex items-end justify-between gap-4"><div><span className="eyebrow">PRÓXIMO HITO</span><p className="mt-2 font-serif text-3xl text-[#e0c99f]">{current.subscribers} suscriptores</p></div><p className="font-serif text-[#c69b58]">{formatCompact(subscribers)} / {formatCompact(current.subscribers)}</p></div><div className="mt-5 h-3 overflow-hidden border border-[#846133]/50 bg-black"><div className="h-full bg-gradient-to-r from-[#7e4d1e] via-[#c38b3c] to-[#f0c674] shadow-[0_0_18px_#c38b3c]" style={{ width: `${progress}%` }}/></div><div className="mt-4 flex flex-wrap justify-between gap-2 text-sm text-[#8d806d]"><span>Premio: <strong className="text-[#d6b77e]">{current.prize}</strong></span><span>Faltan {remaining} suscriptores</span></div></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button href={siteConfig.social.youtubeSubscribe}>Suscribirse al canal</Button><Button href="/ranking" variant="secondary">Ver ranking de participación</Button></div></div></section>

    <NieblaGiveawaySection/>

    <Section eyebrow="EL CAMINO A LOS 1000" title="Cinco metas. Cinco recompensas." description="Estos son los hitos habituales de World of Warcraft. Funcionan de forma independiente al sorteo especial con Niebla Tattooer."><div className="grid gap-4 md:grid-cols-5">{giveawayMilestones.map((milestone) => { const reached = subscribers >= milestone.subscribers; const active = current.subscribers === milestone.subscribers; return <Card key={milestone.subscribers} className={`relative p-5 ${active ? "border-[#c6984f]/80 shadow-[0_0_28px_rgba(177,119,48,.15)]" : ""}`}><div className="flex items-center justify-between"><span className="font-serif text-3xl text-[#d7b678]">{milestone.subscribers}</span>{reached ? <BadgeCheck size={20} className="text-[#9bba7a]"/> : active ? <Radio size={18} className="text-[#d49c4f]"/> : <Gift size={18} className="text-[#665945]"/>}</div><p className="mt-6 min-h-16 text-sm leading-6 text-[#9a8d79]">{milestone.prize}</p><span className="mt-5 block text-[10px] font-bold tracking-widest text-[#6f624e] uppercase">{reached ? "Hito alcanzado" : active ? "En progreso" : "Próximo"}</span></Card>})}</div></Section>

    <Section eyebrow="HISTORIAL DE SORTEOS" title="Ganadores y sorteos pendientes" description="Un registro público de los hitos alcanzados, sus premios y el estado de cada sorteo."><div className="space-y-4">{giveawayHistory.map((entry) => { const completed = entry.status === "completed"; return <Card className={`relative overflow-hidden p-6 md:p-8 ${completed ? "border-[#88704a]/60" : "border-[#9a6639]/55"}`} key={entry.milestone}><div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-[#d3aa64] to-[#6e431d]"/><div className="grid items-center gap-6 md:grid-cols-[auto_1fr_auto]"><div className={`grid size-16 place-items-center border ${completed ? "border-[#8b744c] bg-[#88703c]/10 text-[#d5b472]" : "border-[#8d5734] bg-[#753318]/15 text-[#d28a5c]"}`}>{completed ? <Award size={28}/> : <Clock3 size={27}/>}</div><div><div className="flex flex-wrap items-center gap-3"><Badge>{entry.label}</Badge><span className={`text-[10px] font-bold tracking-widest uppercase ${completed ? "text-[#8fa274]" : "text-[#c17a51]"}`}>{completed ? "Sorteo completado" : "Sorteo pendiente"}</span></div><h3 className="mt-3 font-serif text-2xl text-[#dec69d]">{entry.title}</h3><p className="mt-2 text-sm text-[#9a8b75]">Premio: <strong className="text-[#c9aa75]">{entry.prize}</strong></p><p className="mt-2 text-sm leading-6 text-[#776d60]">{entry.note}</p></div><div className="min-w-52 border-l border-[#6f5636]/40 pl-6 md:text-right"><span className="eyebrow">{completed ? "GANADOR" : "ESTADO"}</span>{completed ? <><p className="mt-2 font-serif text-2xl text-[#e0c392]">{entry.winner}</p><p className="mt-1 text-xs text-[#8c7d68]">{entry.username}</p><a href="/ranking" className="mt-3 inline-flex items-center gap-1 text-xs text-[#bd914e] hover:text-[#e0b66f]"><Trophy size={13}/> Nº 1 del ranking</a></> : <><p className="mt-2 font-serif text-xl text-[#d39a6a]">Por celebrar</p><p className="mt-1 text-xs text-[#806e5d]">Ganador aún no seleccionado</p></>}</div></div></Card>})}</div></Section>

    <Section eyebrow="SISTEMA DE PUNTOS" title="Participar más. Participar mejor." description="Los puntos representan actividad real. Repetir mensajes o generar spam no mejora una participación."><div className="grid gap-4 md:grid-cols-2">{pointsRules.map((rule, index) => <Card className="flex gap-5 p-6" key={rule.label}><div className="grid size-12 shrink-0 place-items-center border border-[#8b6637]/50 bg-[#9b6222]/10 text-[#d5a85f]">{index < 2 ? <MessageCircle size={20}/> : <Radio size={20}/>}</div><div><div className="flex items-center gap-3"><h3 className="font-serif text-xl text-[#dbc39a]">{rule.label}</h3><Badge>{rule.points} puntos</Badge></div><p className="mt-2 text-sm leading-6 text-[#7f7567]">{rule.detail}</p></div></Card>)}</div><Card className="mt-5 border-[#72532e]/50 p-6"><div className="flex gap-4"><ShieldCheck className="shrink-0 text-[#c69a53]"/><p className="text-sm leading-7 text-[#918572]"><strong className="text-[#d4bd96]">Regla fundamental:</strong> SotaKun, como propietario del canal, queda excluido del ranking. El sistema busca reconocer constancia y aportaciones de calidad, no volumen artificial.</p></div></Card></Section>

    <Section eyebrow="PARTICIPACIÓN GENERAL" title="Tres formas de formar parte" description="Estas acciones explican cómo participar en la comunidad y generar puntos. Para el sorteo especial basta con aparecer en el ranking y superar los 5 puntos; la suscripción y Discord no son requisitos."><div className="grid gap-5 md:grid-cols-3">{[[Users,"Sigue el canal","Descubre el contenido oficial de SotaKun."],[MessageCircle,"Únete al Discord","Forma parte del espacio oficial de la comunidad si lo deseas."],[Trophy,"Participa","Comenta y acompaña los directos de forma auténtica."]].map(([Icon,title,text]) => { const ItemIcon = Icon as typeof Users; return <Card className="p-7" key={title as string}><ItemIcon className="text-[#c99b52]"/><h3 className="mt-6 font-serif text-2xl text-[#ddc49a]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#817667]">{text as string}</p><Check className="mt-6 text-[#758f62]" size={18}/></Card>})}</div></Section>

    {adminPanel && <Section eyebrow="CONTROL DEL SORTEO" title="Mesa de extracción" description="Panel privado para preparar el censo, excluir usuarios y seleccionar un ganador.">{adminPanel}</Section>}

  </>;
}
